### ISSUE TITLE
Программы

### ISSUE THREAD

**Issue by D31DARA** [ufgf/Notice-me-Senpai#1]
Сделай что бы могла открывать локальные программы

**Comment by ufgf** [comment]
Дайте пример хотя-бы 1-3 программ для запуска

**Comment by ufgf** [comment]
В течении 4 дней ответа не последовало
Однако лучше реализовать тот функционал (например калькулятора) в самой консоли

Если есть личное предложение например, обращайтесь по Дискорду/Телеграмму которые указаны в инфо у консоли
